server:
  port: 9001
  error:
    include-message: always
    include-exception: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

